### ISSUE TITLE
Using remote methods for component storage

### ISSUE THREAD

**Issue by voitau** [strongloop/loopback-connector-remote#24] opened 2015-11-07 08:08 UTC
Component storage container declares upload and download methods. However, none of them works as expected if connected remotely to. For upload - form data seems not to be passed to the remote server properly. For download the "Content-Type" value is replaced by "application/vnd.api+json".

Is remote connector supposed to work with binary data? Or is it JSON only?

**Comment by richardpringle** [comment] 2015-11-10 17:03
Hey @voitau, a couple of things to help resolve your issue: if you just want your question answered, please ask it in one of the 3 options in [here](https://github.com/strongloop/loopback/wiki/Questions) (I don't have the answer, but someone definitely will in there).

As for your bug, if you could follow [bug report procedure](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report), I can try to reproduce your issue and help you resolve it (or find someone who can).

**Comment by voitau** [comment] 2015-11-12 03:27
@richardpringle, https://github.com/voitau/loopback-sandbox.git - this is a fork with the code to reproduce. 

Steps: 
Storage Server:
- create a directory for container;
- start a server (server/server.js);
- upload an image to a created container.

Storage Client:
- start a server (storage-client/server/server.js);
- try to download the image (uploaded before) - empty result, 204 response code;
- try to upload a new image - image not downloaded, 200 response code, empty result:
```
{
  "result": {
    "files": {},
    "fields": {}
  }
}
```
As far as I understand, remote communication works, but it does not transfer binary data properly.

Additional notices:
1. Setting up remote methods for a client. To be able to connect, I had to copy remote methods declaration to container.js like from storage component (may be this is an issue, please advise what is a correct way if it is not):
```javascript
module.exports = function(Container) {

  Container.download = function(container, file, res, cb) {
    cb();
  };

  Container.remoteMethod('upload', {
    http: {verb: 'post', path: '/:container/upload'},
    accepts: [
      {arg: 'req', type: 'object', 'http': {source: 'req'}},
      {arg: 'res', type: 'object', 'http': {source: 'res'}}
    ],
    returns: {arg: 'result', type: 'object'}
  });

  Container.upload = function(req, res, options, cb) {
    cb();
  };

  Container.remoteMethod('download', {
    http: { verb: 'get', path: '/:container/download/:file'},
    accepts: [
      {arg: 'container', type: 'string', 'http': {source: 'path'}},
      {arg: 'file', type: 'string', 'http': {source: 'path'}},
      {arg: 'res', type: 'object', 'http': {source: 'res'}}
    ],
    returns: {arg: 'result', type: 'object'}
  });
};
```

2. Debugging. When you use `DEBUG=loopback:*`, you can see that access is properly granted to methods, and actually, that's it, nothing related to storage component. (does not matter if you call methods locally or remotely).

**Comment by richardpringle** [comment] 2015-11-16 21:45
@voitau, sorry about the delay. So to me, it looks like component-storage methods aren't binding to the container model on the client-side. Which means that the remote connector is not compatible with "storage" data-source. 

@raymondfeng, @ritch, should lb-connector-remote be compatible with the component-storage data-source?

@voitau I am closing this issue and have opened [issue-25](https://github.com/strongloop/loopback-connector-remote/issues/25) as a feature request.

**Closed by richardpringle** 2015-11-16 21:45 UTC
Labels: triage
